# vi:syntax=yaml.ansible
---
# Use npm user config
- name: Get current npm prefix
  ansible.builtin.command:
    cmd: "npm config --user get prefix"
  register: npm_prefix_check
  changed_when: false
- name: Set npm prefix
  when: "'/'.join((ansible_env.HOME,'.npm')) != npm_prefix_check.stdout"
  ansible.builtin.command:
    cmd: "npm config --user set prefix {{ ansible_env.HOME }}/.npm"
  changed_when: true
