- name: Install 3270 font
  block:
    - name: Get latest release of 3270
      uri:
        headers:
          Accept: application/vnd.github.v3+json
        url: https://api.github.com/repos/rbanffy/3270font/releases/latest
      register: font_3270_github_latest_release
    - name: Check if 3270 font is installed
      stat:
        path: "~/.local/share/fonts/3270-{{ latest }}"
      vars:
        latest: "{{ font_3270_github_latest_release.json.tag_name }}"
      register: font_3270_exists
    - name: Install 3270 font
      when: font_3270_exists.stat.exists == False
      block:
        - name: Create temporary file to store 3270
          ansible.builtin.tempfile:
            state: directory
            suffix: font-3270
          register: font_3270_temp
        - name: Download and Extract 3270 font
          unarchive:
            src: "{{ download_url }}"
            dest: "{{ font_3270_temp.path }}"
            remote_src: true
          vars:
            query: "assets[0].browser_download_url"
            download_url: "{{ font_3270_github_latest_release.json | community.general.json_query(query) }}"
        - name: Find downloaded 3270 font files
          find:
            paths: "{{ font_3270_temp.path }}"
            patterns: "^.*\\.otf$"
            use_regex: true
          vars:
            latest: "{{ font_3270_github_latest_release.json.tag_name }}"
          register: downloaded_3270_fonts
        - name: Install 3270 font
          copy:
            src: "{{ item.path }}"
            dest: "~/.local/share/fonts/3270-{{ latest }}/"
          register: font_3270_installed
          loop: "{{ downloaded_3270_fonts.files }}"
          vars:
            latest: "{{ font_3270_github_latest_release.json.tag_name }}"
        - name: Remove temporary 3270 files
          file:
            path: "{{ font_3270_temp.path }}"
            state: absent
        - name: Cleanup old 3270 fonts
          when: font_3270_installed.changed
          block:
            - name: Find non-latest 3270 font
              find:
                excludes:
                  - "^3270.*-{{ latest | regex_escape('posix_basic') }}$"
                paths: "~/.local/share/fonts/"
                patterns: "^3270.*$"
                use_regex: true
              vars:
                latest: "{{ font_3270_github_latest_release.json.tag_name }}"
              register: old_3270_fonts
            - name: Remove old 3270 fonts
              file:
                path: "{{ item.path }}"
                state: absent
              with_items: "{{ old_3270_fonts.files }}"
