- name: Install Fixedsys Excelsior font
  block:
    - name: Get latest release of Fixedsys Excelsior
      ansible.builtin.uri:
        headers:
          Accept: application/vnd.github.v3+json
        url: https://api.github.com/repos/kika/fixedsys/releases/latest
      register: font_fe_github_latest_release
    - name: Install Fixedsys Excelsior font
      ansible.builtin.get_url:
        url: "{{ download_url }}"
        dest: "~/.local/share/fonts/fixedsys-excelsior-{{ latest }}.tff"
      register: font_fixedsys_excelsior_installed
      vars:
        latest: "{{ font_fe_github_latest_release.json.tag_name }}"
        remote_filename: "FSEX{{ latest | regex_replace('^v?(\\d+)\\.(\\d+).*$', '\\1\\2') }}.ttf"
        query: "assets[?name=='{{ remote_filename }}'].browser_download_url | [0]"
        download_url: "{{ font_fe_github_latest_release.json | community.general.json_query(query) }}"
    - name: Cleanup old Fixedsys Excelsior fonts
      when: font_fixedsys_excelsior_installed.changed
      block:
        - name: Find non-latest Fixedsys Excelsior font
          ansible.builtin.find:
            excludes:
              - "fixedsys-excelsior-{{ latest | regex_escape('posix_basic') }}.tff"
            paths: "~/.local/share/fonts/"
            patterns: "^fixedsys-excelsior.*\\.tff$"
            use_regex: true
          vars:
            latest: "{{ font_fe_github_latest_release.json.tag_name }}"
          register: old_fixedsys_excelsior_fonts
        - name: Remove old Fixedsys Excelsior font
          ansible.builtin.file:
            path: "{{ item.path }}"
            state: absent
          with_items: "{{ old_fixedsys_excelsior_fonts.files }}"
