# vi:syntax=yaml.ansible
---
- name: Environment Setup
  hosts: posix
  gather_facts: true
  become: false
  environment:
    # ensure local bin is in path
    PATH: "{{ ansible_env.PATH }}:/home/{{ ansible_user_id }}/.local/bin"
  vars:
    linux_desktop: "{{ ('XDG_CURRENT_DESKTOP' in ansible_env) and (ansible_env.XDG_CURRENT_DESKTOP|length > 0) }}"
    thinkpad: "{{ ansible_product_version is regex('ThinkPad') }}"
  tasks:
    - name: Install and configure platform specific settings
      include_tasks: "platform/{{ ansible_distribution }}.yaml"
    - name: Install hostess cli
      ansible.builtin.command:
        cmd: go get -u github.com/cbednarski/hostess
        creates: ~/.go/bin/hostess
      environment:
        GOPATH: "{{ ansible_env.HOME }}/.go"
    # Language package manager content, should be managed by a package config
    # file for contents rather than managed here
    - name: Register npm major version
      ansible.builtin.shell:
        cmd: |
          npm --version | awk 'BEGIN { FS = "." } ; { print $1 }'
      register: npm_version
      changed_when: false
    - name: NPM configuration (globalconfig) (versions <7)
      include_tasks: "npm/globalconfig.yaml"
      when: npm_version.stdout | int < 7
    - name: NPM configuration (userconfig) (versions 7+)
      include_tasks: "npm/userconfig.yaml"
      when: npm_version.stdout | int >= 7
    - name: Update composer packages
      community.general.composer:
        no_dev: false
        command: update
        global_command: true
      environment:
        COMPOSER_HOME: "{{ ansible_env.HOME }}/.config/composer"
    - name: package sources
      ansible.builtin.git:
        repo: https://github.com/{{ item.owner }}/{{ item.repo }}
        dest: ~/.local/src/{{ item.repo }}
        depth: 1
        force: true # disregard local changes
      loop:
        - owner: dexpota
          repo: kitty-themes
        - owner: kittykatt
          repo: screenfetch
        - owner: muennich
          repo: urxvt-perls
    - name: vim bundles
      ansible.builtin.git:
        repo: https://github.com/{{ item.owner }}/{{ item.repo }}
        dest: ~/.vim/bundle/{{ item.repo }}
        depth: 1
        force: true # disregard local changes
      loop:
        - owner: adelarsq
          repo: vim-matchit
        - owner: cespare
          repo: vim-toml
        - owner: chrisbra
          repo: csv.vim
        - owner: editorconfig
          repo: editorconfig-vim
        - owner: fatih
          repo: vim-go
        - owner: flazz
          repo: vim-colorschemes
        - owner: idanarye
          repo: vim-vebugger
        - owner: leafgarland
          repo: typescript-vim
        - owner: lumiliet
          repo: vim-twig
        - owner: martinda
          repo: jenkinsfile-vim-syntax
        - owner: mattn
          repo: emmet-vim
        - owner: pearofducks
          repo: ansible-vim
        - owner: plasticboy
          repo: vim-markdown
        - owner: quramy
          repo: tsuquyomi
        - owner: rust-lang
          repo: rust.vim
        - owner: ryanoasis
          repo: vim-devicons
        - owner: sbdchd
          repo: neoformat
        - owner: scrooloose
          repo: nerdtree
        - owner: shougo
          repo: vimproc.vim
        - owner: towolf
          repo: vim-helm
        - owner: tpope
          repo: vim-fugitive
        - owner: tpope
          repo: vim-liquid
        - owner: vim-syntastic
          repo: syntastic
- name: Non-local updates
  # localhost takes care of itself outside of ansible
  hosts: "posix:!localhost"
  gather_facts: false
  become: false
  tasks:
    - name: Ensure yadm is up to date
      ansible.builtin.shell:
        cmd: "yadm fetch -a && yadm reset --hard && yadm merge origin/main"
      register: yadm_update
      changed_when: "yadm_update.stdout is not regex('Already up to date')"
- name: Windows setup
  hosts: windows
  gather_facts: false
  become: false
  tasks:
    # python modules will not work on a windows host,
    # see https://docs.ansible.com/ansible/latest/user_guide/windows_faq.html#can-i-run-python-modules-on-windows-hosts
    - name: Install Windows packages
      chocolatey.chocolatey.win_chocolatey:
        name:
          - 7zip
          - Firefox
          - Minikube
          - discord
          - docker
          - docker-cli
          - foobar2000
          - git
          - keepassxc
          - keybase
          - kubernetes-cli
          - mpv
          - obs
          - openjdk
          - powershell-core
          - python
          - sharpkeys
          - synergy
          - vim
          - vlc
          - vscode
          - winscp
          - wsl2
        state: present
    - name: install the Win32-OpenSSH service
      chocolatey.chocolatey.win_chocolatey:
        name: openssh
        package_params: /SSHServerFeature
        state: present
    # TODO: ensure key is installed, permission set
    # https://docs.ansible.com/ansible/2.9/modules/win_acl_module.html#win-acl-module
    # https://stackoverflow.com/questions/16212816/setting-up-openssh-for-windows-using-public-key-authentication/50502015#50502015
    - name: Set the default shell to PowerShell
      ansible.windows.win_regedit:
        path: HKLM:\SOFTWARE\OpenSSH
        name: DefaultShell
        data: 'C:\Program Files\powershell\7\pwsh.exe'
        type: string
        state: present
    - name: Enable remote desktop
      ansible.windows.win_regedit:
        path: 'HKLM:\System\CurrentControlSet\Control\Terminal Server'
        name: fDenyTSConnections
        data: 0
        type: dword
        state: present
    - name: Firewall rule to allow remote desktop
      win_firewall_rule:
        name: Remote Desktop
        action: allow
        state: present
        enabled: yes
    - name: Upgrade installed packages
      chocolatey.chocolatey.win_chocolatey:
        name: all
        state: latest
