- name: Workstation Setup
  hosts: localhost
  gather_facts: true
  become: false
  tasks:
    # Gather and print out system details
    - name: System details
      debug:
        msg: "{{ item }}"
      with_items:
        - "{{ ansible_distribution }}"
        - "{{ ansible_distribution_release }}"
        - "{{ ansible_distribution_version }}"
        - "{{ ansible_distribution_major_version }}"
    - name: Install and configure platform specific settings
      include_tasks: "platform/{{ ansible_distribution }}.yaml"
    - name: Install hostess cli
      command:
        cmd: go get -u github.com/cbednarski/hostess
        creates: ~/.go/bin/hostess
      environment:
        GOPATH: "{{ lookup('env','HOME') }}/.go"
    # Language package manager content, should be managed by a package config
    # file for contents rather than managed here
    - name: Register npm config file
      command:
        cmd: 'echo "$HOME/.npmrc"'
      register: npm_globalconfig
      changed_when: false
    - name: Get npm globalconfig file
      command:
        cmd: "npm config --global get globalconfig"
      register: npm_globalconfig_check
      changed_when: false
    # bizarre setting where you need to set the globalconfig in the file you're
    # using for globalconfig
    - name: Set npm globalconfig
      when: "npm_globalconfig.stdout != npm_globalconfig_check.stdout"
      lineinfile:
        path: "{{ npm_globalconfig.stdout }}"
        regexp: "^globalconfig"
        line: "globalconfig={{ npm_globalconfig.stdout }}"
    - name: Register npm prefix
      command:
        cmd: 'echo "$HOME/.npm"'
      register: npm_prefix
      changed_when: false
    - name: Get npm prefix
      command:
        cmd: "npm config --global get prefix"
      register: npm_prefix_check
      changed_when: false
    - name: Set npm prefix
      when: "npm_prefix.stdout != npm_prefix_check.stdout"
      command:
        cmd: "npm config set prefix {{ npm_prefix.stdout }}"
      changed_when: true
    - name: Get pnpm prefix
      command:
        cmd: "npm config --global get pnpm-prefix"
      register: pnpm_prefix_check
      changed_when: false
    - name: Set pnpm prefix
      when: "npm_prefix.stdout != pnpm_prefix_check.stdout"
      command:
        cmd: "npm config --global set pnpm-prefix {{ npm_prefix.stdout }}"
      changed_when: true
    - name: Update pnpm packages
      command:
        cmd: 'npx pnpm update --dir "$HOME/.npm/pnpm-global/3"'
      register: pnpm_update
      changed_when: '"Already up-to-date" not in pnpm_update.stdout_lines'
    - name: Update composer packages
      community.general.composer:
        no_dev: false
        command: update
        global_command: true
      environment:
        COMPOSER_HOME: "{{ lookup('env','HOME') }}/.config/composer"
    - name: Update yadm submodules
      command:
        cmd: "yadm submodule update --init --remote"
      register: yadm_update
      changed_when: 'yadm_update.stdout != ""'
