# vi:syntax=yaml.ansible
---
- name: Windows setup
  hosts: windows
  gather_facts: false
  become: false
  tasks:
    # python modules will not work on a windows host,
    # see https://docs.ansible.com/ansible/latest/user_guide/windows_faq.html#can-i-run-python-modules-on-windows-hosts
    - name: Install Windows packages
      chocolatey.chocolatey.win_chocolatey:
        name:
          - 7zip
          - discord
          - foobar2000
          - gh
          - git
          - keepassxc
          - librewolf
          - mactype
          - microsoft-windows-terminal
          - mpv
          - nmap
          - obs
          - powershell-core
          - powertoys
          - python
          - sharpkeys
          - synergy
          - transgui
          - vim
          - vlc
          - vscode
          - wezterm
          - winscp
          - wsl2
        state: present
    - name: install the Win32-OpenSSH service
      chocolatey.chocolatey.win_chocolatey:
        name: openssh
        package_params: /SSHServerFeature
        state: present
    # TODO: ensure key is installed, permission set
    # https://docs.ansible.com/ansible/2.9/modules/win_acl_module.html#win-acl-module
    # https://stackoverflow.com/questions/16212816/setting-up-openssh-for-windows-using-public-key-authentication/50502015#50502015
    - name: Set the default shell to PowerShell
      ansible.windows.win_regedit:
        path: HKLM:\SOFTWARE\OpenSSH
        name: DefaultShell
        data: 'C:\Program Files\powershell\7\pwsh.exe'
        type: string
        state: present
    - name: Enable remote desktop
      ansible.windows.win_regedit:
        path: 'HKLM:\System\CurrentControlSet\Control\Terminal Server'
        name: fDenyTSConnections
        data: 0
        type: dword
        state: present
    - name: Firewall rule to allow remote desktop
      community.windows.win_firewall_rule:
        name: Remote Desktop
        action: allow
        state: present
        enabled: yes
    - name: Upgrade installed packages
      chocolatey.chocolatey.win_chocolatey:
        name: all
        state: latest
    - name: Start WSL and get IP address
      when: false
      win_command: "wsl hostname -I"
      changed_when: false
      register: wsl_hostname
    - name: Add portproxy to wsl for IPv4
      when: false
      win_command: "netsh interface portproxy add v4tov4 listenport=8022 connectaddress={{ wsl_hostname.stdout | trim }} connectport=8022"
      changed_when: false
    - name: Add portproxy to wsl for IPv6
      when: false
      win_command: "netsh interface portproxy add v6tov4 listenport=8022 connectaddress={{ wsl_hostname.stdout | trim }} connectport=8022"
      changed_when: false
    - name: Add firewall rule for wsl
      when: false
      community.windows.win_firewall_rule:
        name: WSL SSH
        localport: 8022
        action: allow
        direction: in
        protocol: tcp
        profiles: domain,private,public
        state: present
        enabled: yes
    - name: Start WSL SSH
      when: false
      win_command: "wsl -u root service ssh start"
      changed_when: false
- name: Environment Setup
  hosts: posix
  gather_facts: true
  become: false
  environment:
    # ensure local bin is in path
    PATH: "{{ ansible_env.PATH }}:/home/{{ ansible_user_id }}/.local/bin"
  vars:
    apple_silicon: "{{ (ansible_distribution == 'MacOSX') and (ansible_architecture == 'arm64') }}"
    linux_desktop: "{{ ('XDG_CURRENT_DESKTOP' in ansible_env) and (ansible_env.XDG_CURRENT_DESKTOP|length > 0) }}"
    thinkpad: "{{ ansible_product_version is regex('ThinkPad') }}"
  handlers:
    - name: restart_cockpit
      become: true
      ansible.builtin.service:
        name: cockpit
        state: restarted
    - name: restart_firewalld
      become: true
      ansible.builtin.service:
        name: firewalld
        state: restarted
    - name: restart_pcp
      become: true
      ansible.builtin.service:
        name: "{{ item }}"
        state: restarted
      loop:
        - pmcd
        - pmlogger
    - name: restart_sshd
      become: true
      ansible.builtin.service:
        name: sshd
        state: restarted
  tasks:
    - name: Install and configure platform specific settings
      include_tasks: "platform/{{ ansible_distribution }}.yaml"
    # Language package manager content, should be managed by a package config
    # file for contents rather than managed here
    - name: Register npm major version
      ansible.builtin.shell:
        cmd: |
          npm --version | awk 'BEGIN { FS = "." } ; { print $1 }'
      register: npm_version
      changed_when: false
      failed_when: npm_version.stdout == ""
    - name: NPM configuration (globalconfig) (versions <7)
      include_tasks: "npm/globalconfig.yaml"
      when: npm_version.stdout | int < 7
    - name: NPM configuration (userconfig) (versions 7+)
      include_tasks: "npm/userconfig.yaml"
      when: npm_version.stdout | int >= 7
    - name: Update composer packages
      # composer requires a modern amount of memory to update,
      # so only run on systems with 2gb or more
      when: ansible_memtotal_mb >= 2048
      community.general.composer:
        no_dev: false
        command: update
        global_command: true
      environment:
        COMPOSER_HOME: "{{ ansible_env.HOME }}/.config/composer"
    - name: Install pip packages
      when: ansible_python.version.major >= 3
      ansible.builtin.pip:
        name:
          - git-filter-repo
          # - pyside2
        extra_args: --user
        state: latest
    - name: Install pip packages on older machines
      when: ansible_python.version.major < 3
      ansible.builtin.pip:
        name:
          - git-filter-repo
          - pyside2
        extra_args: --user
        state: latest
      vars:
        ansible_python_interpreter: /usr/bin/env python3
    - name: package sources
      ansible.builtin.git:
        repo: https://github.com/{{ item.owner }}/{{ item.repo }}
        dest: ~/.local/src/{{ item.repo }}
        depth: 1
        force: true # disregard local changes
      loop:
        - owner: dylanaraps
          repo: neofetch
        - owner: muennich
          repo: urxvt-perls
    - name: tmux plugins
      ansible.builtin.git:
        repo: https://github.com/{{ item.owner }}/{{ item.repo }}
        dest: ~/.tmux/plugins/{{ item.repo }}
        depth: 1
        force: true # disregard local changes
      loop:
        - owner: tmux-plugins
          repo: tmux-sensible
        - owner: tmux-plugins
          repo: tpm
    - name: vim plugins
      ansible.builtin.git:
        repo: https://github.com/{{ item.owner }}/{{ item.repo }}
        dest: ~/.vim/pack/git-plugins/start/{{ item.repo }}
        depth: 1
        force: true # disregard local changes
      loop:
        - owner: adelarsq
          repo: vim-matchit
        - owner: cespare
          repo: vim-toml
        - owner: chrisbra
          repo: csv.vim
        - owner: dense-analysis
          repo: ale
        - owner: editorconfig
          repo: editorconfig-vim
        - owner: fatih
          repo: vim-go
        - owner: flazz
          repo: vim-colorschemes
        - owner: idanarye
          repo: vim-vebugger
        - owner: leafgarland
          repo: typescript-vim
        - owner: lumiliet
          repo: vim-twig
        - owner: martinda
          repo: jenkinsfile-vim-syntax
        - owner: mattn
          repo: emmet-vim
        - owner: pearofducks
          repo: ansible-vim
        - owner: plasticboy
          repo: vim-markdown
        - owner: quramy
          repo: tsuquyomi
        - owner: rust-lang
          repo: rust.vim
        - owner: ryanoasis
          repo: vim-devicons
        - owner: scrooloose
          repo: nerdtree
        - owner: shougo
          repo: vimproc.vim
        - owner: towolf
          repo: vim-helm
        - owner: tpope
          repo: vim-fugitive
        - owner: tpope
          repo: vim-liquid
        - owner: tpope
          repo: vim-sensible
- name: Media server setup
  hosts: media-server
  gather_facts: false
  become: false
  handlers:
    - name: restart_plex
      become: true
      ansible.builtin.service:
        name: plexmediaserver
        state: restarted
    - name: restart_transmission
      become: true
      ansible.builtin.service:
        name: transmission-daemon
        state: restarted
    - name: restart_firewalld
      become: true
      ansible.builtin.service:
        name: firewalld
        state: restarted
  tasks:
    - name: Add Plex Yum repo
      become: true
      ansible.builtin.yum_repository:
        name: plex
        description: Plex Yum Repository
        baseurl: https://downloads.plex.tv/repo/rpm/$basearch/
        gpgkey: https://downloads.plex.tv/plex-keys/PlexSign.key
        gpgcheck: true
    - name: Install media server packages
      become: true
      ansible.builtin.dnf:
        name:
          - plexmediaserver
          - transmission-daemon
        state: latest
    - name: Enable plex over firewall
      become: true
      ansible.posix.firewalld:
        zone: public
        service: plex
        permanent: yes
        state: enabled
      notify: restart_firewalld
    - name: Enable transmission over firewall
      become: true
      ansible.posix.firewalld:
        zone: public
        service: transmission-client
        permanent: yes
        state: enabled
      notify: restart_firewalld
    - name: Enable plex service
      become: true
      ansible.builtin.service:
        name: plexmediaserver
        enabled: true
      notify: restart_plex
    - name: Enable transmission daemon
      become: true
      ansible.builtin.service:
        name: transmission-daemon
        enabled: true
      notify: restart_transmission
- name: Non-local updates
  # localhost takes care of itself outside of ansible
  hosts: "posix:!localhost"
  gather_facts: false
  become: false
  tasks:
    - name: Check for yadm repo
      failed_when: false
      changed_when: false # command result is not a change
      ansible.builtin.command:
        cmd: "yadm status"
      register: yadm_status
    - name: Ensure yadm is up to date
      # only run if yadm status is valid
      when: "yadm_status.rc == 0"
      ansible.builtin.shell:
        cmd: "yadm fetch -a && yadm reset --hard && yadm merge origin/main"
      register: yadm_update
      changed_when: "yadm_update.stdout is not regex('Already up to date')"
