- name: Workstation Setup
  hosts: localhost
  gather_facts: true
  become: false
  tasks:
    - name: Install and configure platform specific settings
      include_tasks: "platform/{{ ansible_distribution }}.yaml"
    - name: Install hostess cli
      command:
        cmd: go get -u github.com/cbednarski/hostess
        creates: ~/.go/bin/hostess
      environment:
        GOPATH: "{{ lookup('env','HOME') }}/.go"
    # Language package manager content, should be managed by a package config
    # file for contents rather than managed here
    - name: Register npm major version
      shell:
        cmd: |
          npm --version | awk 'BEGIN { FS = "." } ; { print $1 }'
      register: npm_version
      changed_when: false
    - name: NPM configuration (globalconfig) (versions <7)
      include_tasks: "npm/globalconfig.yaml"
      when: npm_version.stdout | int < 7
    - name: NPM configuration (userconfig) (versions 7+)
      include_tasks: "npm/userconfig.yaml"
      when: npm_version.stdout | int >= 7
    - name: Update composer packages
      community.general.composer:
        no_dev: false
        command: update
        global_command: true
      environment:
        COMPOSER_HOME: "{{ lookup('env','HOME') }}/.config/composer"
    - name: Update yadm submodules
      command:
        cmd: "yadm submodule update --init --remote"
      register: yadm_update
      changed_when: 'yadm_update.stdout != ""'
