# vi:syntax=yaml.ansible
#########
#
# Use ansible galaxy tools to use extensions to ansible
#
# Run this to install dependencies:
#
# ```sh
# ansible-galaxy collection install -r requirements.yaml
# ```
#
---
collections:
  - ansible.posix
  - ansible.windows
  - chocolatey.chocolatey
  - community.general
  - community.windows
