"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = """$character"""
right_format = """$all"""

[package]
disabled = true

[php]
disabled = true

[kubernetes]
disabled = false

[nodejs]
disabled = true
