- name: Install YADM repo GPG key
  become: true
  rpm_key:
    key: https://copr-be.cloud.fedoraproject.org/results/cdayjr/yadm/pubkey.gpg
    state: present
- name: Install YADM repo
  become: yes
  command: "dnf copr enable -y cdayjr/yadm"
  args:
    creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:cdayjr:yadm.repo
    warn: false
- name: Install distribution GPG keys
  become: true
  dnf:
    name: "distribution-gpg-keys"
    state: latest
- name: Install RPMFusion (free) repo GPG key
  become: true
  rpm_key:
    key: "/usr/share/distribution-gpg-keys/rpmfusion/RPM-GPG-KEY-rpmfusion-free-fedora-{{ ansible_distribution_major_version }}-primary"
    state: present
- name: Install RPMFusion (free)
  become: true
  dnf:
    name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
- name: Install RPMFusion (nonfree) repo GPG key
  become: true
  rpm_key:
    key: "/usr/share/distribution-gpg-keys/rpmfusion/RPM-GPG-KEY-rpmfusion-nonfree-fedora-{{ ansible_distribution_major_version }}"
    state: present
- name: Install RPMFusion (nonfree)
  become: true
  dnf:
    name: "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
- name: Install "Development Tools" DNF package group
  become: true
  dnf:
    name: "@Development Tools"
    state: latest
- name: Install appstream-data for rpmfusion packages
  become: true
  dnf:
    name: "@core"
    state: latest
- name: Install multimedia plugins from RPMFusion
  become: true
  dnf:
    name: "@multimedia"
    state: latest
    install_weak_deps: false
    exclude: PackageKit-gstreamer-plugin
- name: Install sound and video complement packages from RPMFusion
  become: true
  dnf:
    name: "@sound-and-video"
    state: latest
- name: Install tainted rpmfusion packages
  become: true
  dnf:
    name: rpmfusion-free-release-tainted
    state: latest
- name: Install CLI packages
  become: true
  dnf:
    name:
      - ImageMagick
      - bat
      - cargo
      - ccze
      - composer
      - curl
      - fd-find
      - golang
      - jq
      - lsd
      - mosh
      - mycli
      - nmap
      - nodejs
      - p7zip
      - php
      - php-bcmath
      - php-cli
      - php-devel
      - php-json
      - php-mbstring
      - powerline
      - powerline-fonts
      - procs
      - python3-github3py
      - rclone
      - ripgrep
      - rsync
      - rust
      - tmux-powerline
      - tokei
      - trash-cli
      - unar
      - vim
      - vim-powerline
      - weechat
      - wget
      - yadm
      - zsh
    state: latest
- name: Set user shell
  become: true
  user:
    name: "{{ lookup('env','USER') }}"
    shell: /usr/bin/zsh
    state: present
- name: bottom Repo
  become: true
  command: "dnf copr enable -y atim/bottom"
  args:
    creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:atim:bottom.repo
    warn: false
  when: ansible_distribution_major_version | int >= 32
  register: bottom_repo
- name: Install bottom from bottom repo
  become: true
  dnf:
    name:
      - bottom
    state: latest
  when: bottom_repo is not skipped
- name: Install desktop packages
  become: true
  dnf:
    name:
      - calibre
      - chromium
      - chromium-libs-media-freeworld
      - discord
      - exfat-utils
      - feh
      - firefox
      - flac123
      - fuse-exfat
      - gimp
      - gnome-tweaks
      - gvfs-smb
      - i3
      - i3lock
      - i3status
      - i3status
      - keepassxc
      - kitty
      - konsole
      - lm_sensors
      - pandoc
      - pinta
      - python3-streamlink
      - redshift-gtk
      - rxvt-unicode
      - steam
      - sway
      - synergy
      - tlp
      - tlp-rdw
      - transmission-remote-gtk
      - wl-clipboard
      - xsel
      - youtube-dl
    state: latest
- name: Keybase Repo
  become: true
  dnf:
    name: "https://prerelease.keybase.io/keybase_amd64.rpm"
    state: present
- name: Keybase setup
  command:
    cmd: keybase ctl autostart --enable
  register: keybase_result
  changed_when: "keybase_result.stdout != ''"
- name: ThinkPad battery tools
  block:
    - name: Install ThinkPad repo GPG key
      become: true
      rpm_key:
        key: "https://repo.linrunner.de/fedora/tlp/repos/RPM-GPG-KEY-tlp-fedora-{{ ansible_distribution_major_version }}-primary"
        state: present
    - name: Install ThinkPad repo
      become: true
      dnf:
        name: "https://repo.linrunner.de/fedora/tlp/repos/releases/tlp-release.fc{{ ansible_distribution_major_version }}.noarch.rpm"
        state: present
    - name: Install ThinkPad packages
      become: true
      package:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
          - akmod-tp_smapi
          - akmod-acpi_call
          - kernel-devel
- name: Install media packages
  become: yes
  package:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - flac123
      - libdvdcss
      - vlc
      - mpv
# Fonts
- name: Install base font packages
  become: true
  dnf:
    name:
      - adobe-source-code-pro-fonts
      - adobe-source-han-code-jp-fonts
      - adobe-source-han-mono-fonts
      - adobe-source-han-sans-cn-fonts
      - adobe-source-han-sans-jp-fonts
      - adobe-source-han-sans-kr-fonts
      - adobe-source-han-sans-tw-fonts
      - adobe-source-han-serif-cn-fonts
      - adobe-source-han-serif-jp-fonts
      - adobe-source-han-serif-kr-fonts
      - adobe-source-han-serif-tw-fonts
      - adobe-source-sans-pro-fonts
      - adobe-source-serif-pro-fonts
      - bitstream-vera-fonts-all
      - cascadia-code-fonts
      - cascadia-code-pl-fonts
      - cascadia-mono-fonts
      - cascadia-mono-pl-fonts
      - comic-neue-angular-fonts
      - comic-neue-fonts
      - dejavu-fonts-all
      - fontawesome-fonts
      - google-android-emoji-fonts
      - google-arimo-fonts
      - google-carlito-fonts
      - google-cousine-fonts
      - google-droid-sans-fonts
      - google-droid-sans-mono-fonts
      - google-droid-serif-fonts
      - google-go-fonts
      - google-go-mono-fonts
      - google-go-smallcaps-fonts
      - google-noto-cjk-fonts
      - google-noto-emoji-color-fonts
      - google-noto-emoji-fonts
      - google-noto-kufi-arabic-fonts
      - google-noto-music-fonts
      - google-noto-naskh-arabic-fonts
      - google-noto-naskh-arabic-ui-fonts
      - google-noto-nastaliq-urdu-fonts
      - google-noto-sans-adlam-fonts
      - google-noto-sans-adlam-unjoined-fonts
      - google-noto-sans-anatolian-hieroglyphs-fonts
      - google-noto-sans-arabic-fonts
      - google-noto-sans-arabic-ui-fonts
      - google-noto-sans-arabic-ui-vf-fonts
      - google-noto-sans-arabic-vf-fonts
      - google-noto-sans-armenian-fonts
      - google-noto-sans-armenian-vf-fonts
      - google-noto-sans-avestan-fonts
      - google-noto-sans-bamum-fonts
      - google-noto-sans-bassa-vah-fonts
      - google-noto-sans-batak-fonts
      - google-noto-sans-bengali-fonts
      - google-noto-sans-bengali-ui-fonts
      - google-noto-sans-bengali-ui-vf-fonts
      - google-noto-sans-bengali-vf-fonts
      - google-noto-sans-bhaiksuki-fonts
      - google-noto-sans-brahmi-fonts
      - google-noto-sans-buginese-fonts
      - google-noto-sans-buhid-fonts
      - google-noto-sans-canadian-aboriginal-fonts
      - google-noto-sans-canadian-aboriginal-vf-fonts
      - google-noto-sans-carian-fonts
      - google-noto-sans-caucasian-albanian-fonts
      - google-noto-sans-chakma-fonts
      - google-noto-sans-cham-fonts
      - google-noto-sans-cham-vf-fonts
      - google-noto-sans-cherokee-fonts
      - google-noto-sans-cherokee-vf-fonts
      - google-noto-sans-cjk-hk-fonts
      - google-noto-sans-cjk-jp-fonts
      - google-noto-sans-cjk-kr-fonts
      - google-noto-sans-cjk-sc-fonts
      - google-noto-sans-cjk-tc-fonts
      - google-noto-sans-cjk-ttc-fonts
      - google-noto-sans-coptic-fonts
      - google-noto-sans-cuneiform-fonts
      - google-noto-sans-cypriot-fonts
      - google-noto-sans-deseret-fonts
      - google-noto-sans-devanagari-fonts
      - google-noto-sans-devanagari-ui-fonts
      - google-noto-sans-devanagari-ui-vf-fonts
      - google-noto-sans-devanagari-vf-fonts
      - google-noto-sans-display-fonts
      - google-noto-sans-display-vf-fonts
      - google-noto-sans-duployan-fonts
      - google-noto-sans-egyptian-hieroglyphs-fonts
      - google-noto-sans-elbasan-fonts
      - google-noto-sans-ethiopic-fonts
      - google-noto-sans-ethiopic-vf-fonts
      - google-noto-sans-fonts
      - google-noto-sans-georgian-fonts
      - google-noto-sans-georgian-vf-fonts
      - google-noto-sans-glagolitic-fonts
      - google-noto-sans-gothic-fonts
      - google-noto-sans-grantha-fonts
      - google-noto-sans-gujarati-fonts
      - google-noto-sans-gujarati-ui-fonts
      - google-noto-sans-gurmukhi-fonts
      - google-noto-sans-gurmukhi-ui-fonts
      - google-noto-sans-hanunoo-fonts
      - google-noto-sans-hatran-fonts
      - google-noto-sans-hebrew-fonts
      - google-noto-sans-hebrew-vf-fonts
      - google-noto-sans-hk-fonts
      - google-noto-sans-imperial-aramaic-fonts
      - google-noto-sans-inscriptional-pahlavi-fonts
      - google-noto-sans-inscriptional-parthian-fonts
      - google-noto-sans-javanese-fonts
      - google-noto-sans-jp-fonts
      - google-noto-sans-kaithi-fonts
      - google-noto-sans-kannada-fonts
      - google-noto-sans-kannada-ui-fonts
      - google-noto-sans-kannada-ui-vf-fonts
      - google-noto-sans-kannada-vf-fonts
      - google-noto-sans-kayah-li-fonts
      - google-noto-sans-kharoshthi-fonts
      - google-noto-sans-khmer-fonts
      - google-noto-sans-khmer-ui-fonts
      - google-noto-sans-khmer-ui-vf-fonts
      - google-noto-sans-khmer-vf-fonts
      - google-noto-sans-khojki-fonts
      - google-noto-sans-khudawadi-fonts
      - google-noto-sans-kr-fonts
      - google-noto-sans-lao-fonts
      - google-noto-sans-lao-ui-fonts
      - google-noto-sans-lao-ui-vf-fonts
      - google-noto-sans-lao-vf-fonts
      - google-noto-sans-lepcha-fonts
      - google-noto-sans-limbu-fonts
      - google-noto-sans-linear-a-fonts
      - google-noto-sans-linear-b-fonts
      - google-noto-sans-lisu-fonts
      - google-noto-sans-lycian-fonts
      - google-noto-sans-lydian-fonts
      - google-noto-sans-mahajani-fonts
      - google-noto-sans-malayalam-fonts
      - google-noto-sans-malayalam-ui-fonts
      - google-noto-sans-malayalam-ui-vf-fonts
      - google-noto-sans-malayalam-vf-fonts
      - google-noto-sans-mandaic-fonts
      - google-noto-sans-manichaean-fonts
      - google-noto-sans-marchen-fonts
      - google-noto-sans-math-fonts
      - google-noto-sans-meetei-mayek-fonts
      - google-noto-sans-mende-kikakui-fonts
      - google-noto-sans-meroitic-fonts
      - google-noto-sans-miao-fonts
      - google-noto-sans-modi-fonts
      - google-noto-sans-mongolian-fonts
      - google-noto-sans-mono-cjk-hk-fonts
      - google-noto-sans-mono-cjk-jp-fonts
      - google-noto-sans-mono-cjk-kr-fonts
      - google-noto-sans-mono-cjk-sc-fonts
      - google-noto-sans-mono-cjk-tc-fonts
      - google-noto-sans-mono-fonts
      - google-noto-sans-mono-vf-fonts
      - google-noto-sans-mro-fonts
      - google-noto-sans-multani-fonts
      - google-noto-sans-myanmar-fonts
      - google-noto-sans-myanmar-ui-fonts
      - google-noto-sans-myanmar-ui-vf-fonts
      - google-noto-sans-myanmar-vf-fonts
      - google-noto-sans-nabataean-fonts
      - google-noto-sans-new-tai-lue-fonts
      - google-noto-sans-newa-fonts
      - google-noto-sans-nko-fonts
      - google-noto-sans-ogham-fonts
      - google-noto-sans-ol-chiki-fonts
      - google-noto-sans-old-hungarian-fonts
      - google-noto-sans-old-italic-fonts
      - google-noto-sans-old-north-arabian-fonts
      - google-noto-sans-old-permic-fonts
      - google-noto-sans-old-persian-fonts
      - google-noto-sans-old-south-arabian-fonts
      - google-noto-sans-old-turkic-fonts
      - google-noto-sans-oriya-fonts
      - google-noto-sans-oriya-ui-fonts
      - google-noto-sans-osage-fonts
      - google-noto-sans-osmanya-fonts
      - google-noto-sans-pahawh-hmong-fonts
      - google-noto-sans-palmyrene-fonts
      - google-noto-sans-pau-cin-hau-fonts
      - google-noto-sans-phags-pa-fonts
      - google-noto-sans-phoenician-fonts
      - google-noto-sans-psalter-pahlavi-fonts
      - google-noto-sans-rejang-fonts
      - google-noto-sans-runic-fonts
      - google-noto-sans-samaritan-fonts
      - google-noto-sans-saurashtra-fonts
      - google-noto-sans-sc-fonts
      - google-noto-sans-sharada-fonts
      - google-noto-sans-shavian-fonts
      - google-noto-sans-sinhala-fonts
      - google-noto-sans-sinhala-ui-fonts
      - google-noto-sans-sinhala-vf-fonts
      - google-noto-sans-sora-sompeng-fonts
      - google-noto-sans-sundanese-fonts
      - google-noto-sans-syloti-nagri-fonts
      - google-noto-sans-symbols-fonts
      - google-noto-sans-symbols-vf-fonts
      - google-noto-sans-symbols2-fonts
      - google-noto-sans-syriac-eastern-fonts
      - google-noto-sans-syriac-estrangela-fonts
      - google-noto-sans-syriac-fonts
      - google-noto-sans-syriac-western-fonts
      - google-noto-sans-tagalog-fonts
      - google-noto-sans-tagbanwa-fonts
      - google-noto-sans-tai-le-fonts
      - google-noto-sans-tai-tham-fonts
      - google-noto-sans-tai-viet-fonts
      - google-noto-sans-takri-fonts
      - google-noto-sans-tamil-fonts
      - google-noto-sans-tamil-ui-fonts
      - google-noto-sans-tamil-ui-vf-fonts
      - google-noto-sans-tamil-vf-fonts
      - google-noto-sans-tc-fonts
      - google-noto-sans-telugu-fonts
      - google-noto-sans-telugu-ui-fonts
      - google-noto-sans-thaana-fonts
      - google-noto-sans-thaana-vf-fonts
      - google-noto-sans-thai-fonts
      - google-noto-sans-thai-ui-fonts
      - google-noto-sans-thai-ui-vf-fonts
      - google-noto-sans-thai-vf-fonts
      - google-noto-sans-tibetan-fonts
      - google-noto-sans-tifinagh-fonts
      - google-noto-sans-tirhuta-fonts
      - google-noto-sans-ugaritic-fonts
      - google-noto-sans-vai-fonts
      - google-noto-sans-vf-fonts
      - google-noto-sans-warang-citi-fonts
      - google-noto-sans-yi-fonts
      - google-noto-serif-ahom-fonts
      - google-noto-serif-armenian-fonts
      - google-noto-serif-armenian-vf-fonts
      - google-noto-serif-balinese-fonts
      - google-noto-serif-bengali-fonts
      - google-noto-serif-cjk-jp-fonts
      - google-noto-serif-cjk-kr-fonts
      - google-noto-serif-cjk-sc-fonts
      - google-noto-serif-cjk-tc-fonts
      - google-noto-serif-cjk-ttc-fonts
      - google-noto-serif-devanagari-fonts
      - google-noto-serif-display-fonts
      - google-noto-serif-display-vf-fonts
      - google-noto-serif-ethiopic-fonts
      - google-noto-serif-ethiopic-vf-fonts
      - google-noto-serif-fonts
      - google-noto-serif-georgian-fonts
      - google-noto-serif-georgian-vf-fonts
      - google-noto-serif-gujarati-fonts
      - google-noto-serif-gujarati-vf-fonts
      - google-noto-serif-gurmukhi-fonts
      - google-noto-serif-gurmukhi-vf-fonts
      - google-noto-serif-hebrew-fonts
      - google-noto-serif-hebrew-vf-fonts
      - google-noto-serif-jp-fonts
      - google-noto-serif-kannada-fonts
      - google-noto-serif-kannada-vf-fonts
      - google-noto-serif-khmer-fonts
      - google-noto-serif-khmer-vf-fonts
      - google-noto-serif-kr-fonts
      - google-noto-serif-lao-fonts
      - google-noto-serif-lao-vf-fonts
      - google-noto-serif-malayalam-fonts
      - google-noto-serif-myanmar-fonts
      - google-noto-serif-myanmar-vf-fonts
      - google-noto-serif-sc-fonts
      - google-noto-serif-sinhala-fonts
      - google-noto-serif-sinhala-vf-fonts
      - google-noto-serif-tamil-fonts
      - google-noto-serif-tamil-slanted-fonts
      - google-noto-serif-tamil-slanted-vf-fonts
      - google-noto-serif-tamil-vf-fonts
      - google-noto-serif-tc-fonts
      - google-noto-serif-telugu-fonts
      - google-noto-serif-thai-fonts
      - google-noto-serif-thai-vf-fonts
      - google-noto-serif-tibetan-fonts
      - google-noto-serif-tibetan-vf-fonts
      - google-noto-serif-vf-fonts
      - google-roboto-condensed-fonts
      - google-roboto-fonts
      - google-roboto-mono-fonts
      - google-roboto-slab-fonts
      - google-rubik-fonts
      - google-tinos-fonts
      - grimmer-proggy-squaresz-fonts
      - grimmer-proggy-tinysz-fonts
      - ibm-plex-fonts-all
      - jetbrains-mono-fonts-all
      - lato-fonts
      - liberation-mono-fonts
      - mscore-fonts-all
      - opendyslexic-fonts
      - overpass-fonts
      - overpass-mono-fonts
      - twitter-twemoji-fonts
      - ubuntu-title-fonts
      - unifont-fonts
      - wine-arial-fonts
      - wine-courier-fonts
      - wine-fixedsys-fonts
      - wine-fonts
      - wine-marlett-fonts
      - wine-ms-sans-serif-fonts
      - wine-small-fonts
      - wine-symbol-fonts
      - wine-system-fonts
      - wine-tahoma-fonts
      - wine-times-new-roman-fonts
      - wine-webdings-fonts
      - wine-wingdings-fonts
    state: latest
- name: Fedora Beter Fonts Repo
  become: true
  command: "dnf copr enable -y dawid/better_fonts"
  args:
    creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:dawid:better_fonts.repo
    warn: false
  when: ansible_distribution_major_version | int >= 32
  register: better_fonts_repo
- name: Install fonts from better fonts repo
  become: true
  dnf:
    name:
      - courier-prime-fonts
      - ubuntu-fonts
    state: latest
  when: better_fonts_repo is not skipped
- name: Fira Code Fonts Repo
  become: true
  command: "dnf copr enable -y cyfrost/packages"
  args:
    creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:cyfrost:packages.repo
    warn: false
  when: ansible_distribution_major_version | int >= 32
  register: cyfrost_packages_repo
- name: Install fonts from cyfrost packages
  become: true
  dnf:
    name:
      - fira-code-fonts
    state: latest
  when: cyfrost_packages_repo is not skipped
- name: Manual Font Installation
  block:
    - name: Create local fonts diectory
      file:
        path: ~/.local/share/fonts
        state: directory
    - name: Install manual fonts
      include_tasks: "{{ ansible_distribution }}/fonts/{{ font_item }}.yaml"
      loop:
        - "3270"
        - fixedsys_excelsior
        - nerd_fonts
      loop_control:
        loop_var: font_item
    - name: Collect new font installations
      set_fact:
        new_font_installs:
          - "{{ font_3270_installed.changed }}"
          - "{{ font_fixedsys_excelsior_installed.changed }}"
          - "{{ font_nerd_fonts_installed.changed }}"
    - name: Reload font cache
      when: "True in new_font_installs"
      command: "fc-cache -f"
# Fedora final upgrades & cleanup
- name: Upgrade all DNF pacakges
  become: true
  dnf:
    name: "*"
    state: latest
- name: Autoremove unneeded packages installed as dependencies
  become: true
  dnf:
    autoremove: true
    skip_broken: true
    update_cache: true
- name: Install cargo packages
  command:
    cmd: "cargo install {{ item.package }}"
    creates: "~/.cargo/bin/{{ item.bin }}"
  loop:
    - package: sd
      bin: sd
