- name: Install YADM repo GPG key
  become: true
  rpm_key:
    key: https://copr-be.cloud.fedoraproject.org/results/cdayjr/yadm/pubkey.gpg
    state: present
- name: Install YADM repo
  become: yes
  command: "dnf copr enable -y cdayjr/yadm"
  args:
    creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:cdayjr:yadm.repo
    warn: false
- name: Install distribution GPG keys
  become: true
  dnf:
    name: "distribution-gpg-keys"
    state: latest
- name: Install RPMFusion (free) repo GPG key
  become: true
  rpm_key:
    key: "/usr/share/distribution-gpg-keys/rpmfusion/RPM-GPG-KEY-rpmfusion-free-fedora-{{ ansible_distribution_major_version }}-primary"
    state: present
- name: Install RPMFusion (free)
  become: true
  dnf:
    name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
- name: Install RPMFusion (nonfree) repo GPG key
  become: true
  rpm_key:
    key: "/usr/share/distribution-gpg-keys/rpmfusion/RPM-GPG-KEY-rpmfusion-nonfree-fedora-{{ ansible_distribution_major_version }}"
    state: present
- name: Install RPMFusion (nonfree)
  become: true
  dnf:
    name: "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
- name: Install "Development Tools" DNF package group
  become: true
  dnf:
    name: "@Development Tools"
    state: latest
- name: Install appstream-data for rpmfusion packages
  become: true
  dnf:
    name: "@core"
    state: latest
- name: Install multimedia plugins from RPMFusion
  become: true
  dnf:
    name: "@multimedia"
    state: latest
    install_weak_deps: false
    exclude: PackageKit-gstreamer-plugin
- name: Install sound and video complement packages from RPMFusion
  become: true
  dnf:
    name: "@sound-and-video"
    state: latest
- name: Install tainted rpmfusion packages
  become: true
  dnf:
    name: rpmfusion-free-release-tainted
    state: latest
- name: Install CLI packages
  become: true
  dnf:
    name:
      - ccze
      - composer
      - curl
      - golang
      - golang
      - mosh
      - mycli
      - nmap
      - nodejs
      - p7zip
      - php
      - php-bcmath
      - php-cli
      - php-devel
      - php-json
      - php-mbstring
      - powerline
      - powerline-fonts
      - rclone
      - rsync
      - rust
      - tmux-powerline
      - trash-cli
      - unar
      - vim
      - vim-powerline
      - weechat
      - wget
      - yadm
      - zsh
    state: latest
- name: Set user shell
  become: true
  user:
    name: "{{ lookup('env','USER') }}"
    shell: /usr/bin/zsh
    state: present
- name: Install desktop packages
  become: true
  dnf:
    name:
      - calibre
      - chromium
      - chromium-libs-media-freeworld
      - discord
      - exfat-utils
      - feh
      - firefox
      - flac123
      - fuse-exfat
      - gimp
      - gnome-tweaks
      - gvfs-smb
      - i3
      - i3lock
      - i3status
      - i3status
      - keepassxc
      - konsole
      - lm_sensors
      - pandoc
      - pinta
      - python3-streamlink
      - redshift-gtk
      - rxvt-unicode
      - steam
      - sway
      - synergy
      - tlp
      - tlp-rdw
      - transmission-remote-gtk
      - wl-clipboard
      - xsel
      - youtube-dl
    state: latest
- name: Keybase Repo
  become: true
  dnf:
    name: "https://prerelease.keybase.io/keybase_amd64.rpm"
    state: present
- name: Keybase setup
  command:
    cmd: keybase ctl autostart --enable
  register: keybase_result
  changed_when: "keybase_result.stdout != ''"
- name: ThinkPad battery tools
  block:
    - name: Install ThinkPad repo GPG key
      become: true
      rpm_key:
        key: "https://repo.linrunner.de/fedora/tlp/repos/RPM-GPG-KEY-tlp-fedora-{{ ansible_distribution_major_version }}-primary"
        state: present
    - name: Install ThinkPad repo
      become: true
      dnf:
        name: "https://repo.linrunner.de/fedora/tlp/repos/releases/tlp-release.fc{{ ansible_distribution_major_version }}.noarch.rpm"
        state: present
    - name: Install ThinkPad packages
      become: true
      package:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
          - akmod-tp_smapi
          - akmod-acpi_call
          - kernel-devel
- name: Install media packages
  become: yes
  package:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - flac123
      - libdvdcss
      - vlc
      - mpv
# Fonts
- name: Fira Code Fonts Repo
  become: true
  command: "dnf copr enable -y cyfrost/packages"
  args:
    creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:cyfrost:packages.repo
    warn: false
- name: Install font packages
  become: true
  dnf:
    name:
      - cascadia-code-fonts
      - fira-code-fonts
    state: latest
- name: Custom Fonts
  block:
    - name: Create .fonts diectory
      file:
        path: ~/.fonts
        state: directory
    - name: Install FIXEDSYS Excelsior font
      get_url:
        url: https://github.com/kika/fixedsys/releases/download/v3.02.9/FSEX302.ttf
        dest: ~/.fonts/FSEX302.tff
      register: fixedsys_installed
    - name: Reload font cache
      when: fixedsys_installed.changed
      command: "fc-cache"
# Fedora final upgrades & cleanup
- name: Upgrade all DNF pacakges
  become: true
  dnf:
    name: "*"
    state: latest
- name: Autoremove unneeded packages installed as dependencies
  become: true
  dnf:
    autoremove: true
    skip_broken: true
    update_cache: true
